/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "about me",
      "frontmatter": {
        "navbar": false,
        "title": "about me"
      },
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-0d1d523e",
      "path": "/about/",
      "headers": [
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1"
        },
        {
          "level": 3,
          "title": "二级标题1.1",
          "slug": "二级标题1-1"
        },
        {
          "level": 2,
          "title": "一级标题2",
          "slug": "一级标题2"
        },
        {
          "level": 2,
          "title": "一级标题2",
          "slug": "一级标题2-2"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "actionText": "Get Started →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Simplicity First",
            "details": "Minimal setup with markdown-centered project structure helps you focus on writing."
          },
          {
            "title": "Vue-Powered",
            "details": "Enjoy the dev experience of Vue + webpack, use Vue components in markdown, and develop custom themes with Vue."
          },
          {
            "title": "Performant",
            "details": "VuePress generates pre-rendered static HTML for each page, and runs as an SPA once a page is loaded."
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-b34013a0",
      "path": "/"
    },
    {
      "title": "index",
      "frontmatter": {},
      "regularPath": "/youandme.html",
      "relativePath": "youandme.md",
      "key": "v-9cf24692",
      "path": "/youandme.html",
      "headers": [
        {
          "level": 2,
          "title": "index",
          "slug": "index"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "About",
        "link": "/about/"
      },
      {
        "text": "youandme",
        "link": "/youandme"
      },
      {
        "text": "External",
        "link": "https://baidu.com"
      }
    ],
    "sidebar": "auto"
  }
}